nome = str(input('Digite seu nome completo: ')).strip()
ma = nome.upper()
mi = nome.lower()
quant = len(nome) - nome.count(' ')
pri = nome.find(' ')
print(f'Seu nome em letras maiúsculas é: {ma};')
print(f'Seu nome em letras minúsculas é: {mi};')
print(f'Seu nome tem ao todo {quant} letras;')
print(f'Seu primeiro nome tem {pri} letras.')